### ISSUE TITLE
SOLID di Java Spring apakah wajib?

### ISSUE THREAD

**Issue by bailram** [ProgrammerZamanNow/qna#1]
izin bertanya bang eko, waktu pembuatan service menggunakan java spring itu apakah wajib menerapkan SOLID?
saya juga ingin tahu kalau diperusahaan bang eko ini apakah hal ini wajib? (terlepas dari bahasa pemrogramannya) 
terima kasih

**Comment by khannedy** [comment]
dijawab di youtube

**Comment by bailram** [comment]
yee makasih bank eko, ditunggu videonya

**Comment by syahid246** [comment]
Youtube :
[![Apakah SOLID Wajib Digunakan?](https://i.ytimg.com/vi/4YIUo7ZMMlk/maxresdefault.jpg)](https://www.youtube.com/watch?v=4YIUo7ZMMlk)
