### ISSUE TITLE
Apakah kedepan nya untuk posisi Backend membutuhkan low level programming untuk skala menengah ke atas?

### ISSUE THREAD

**Issue by rizkyalam** [ProgrammerZamanNow/qna#11]
Izin bertanya, menurut pak Eko apakah kedepan nya di posisi Backend membutuhkan low level programming untuk skala menengah ke atas di karenakan kita membutuhkan kecepatan yang di tinggi untuk pertukaran data?

**Comment by khannedy** [comment]
https://youtu.be/oJzHEAS_uPg

**Comment by rizkyalam** [comment]
Mohon maaf saya kurang jelas bertanya maksud saya low level programming itu sama seperti pak Eko jelaskan yaitu seperti bahasa Assembly dan C

Terimakasih pak Eko telah menjawab pertanyaan saya
