### ISSUE TITLE
Lebih baik kuliah atau mengikuti bootcamp?

### ISSUE THREAD

**Issue by euxzy** [ProgrammerZamanNow/qna#114]
Halo pak, saya mau bertanya. Untuk menjadi seorang programmer apakah kita harus kuliah? Atau dengan mengikuti bootcamp saja kita sudah bisa menjadi seorang programmer?

**Comment by zycoder142** [comment]
Saya belajar dari youtube udah jadi Programmer :D

**Comment by zycoder142** [comment]
Belajar dari sini aja bro:

https://github.com/sandhikagalih/channel-youtube-programming-dan-teknologi-indonesia

**Comment by amasparera** [comment]
Saya juga otodidak dari YouTube
