### ISSUE TITLE
Tips saat menjadi speaker yang membahas programming

### ISSUE THREAD

**Issue by zuramai** [ProgrammerZamanNow/qna#12]
Halo, apakah menurut mas Eko ada hal-hal yang perlu diperhatikan saat menjadi speaker dalam sebuah event dengan materi seputar programming? Terima kasih.

**Comment by khannedy** [comment]
https://www.youtube.com/watch?v=Tl2RA9Mxi7Q&ab_channel=ProgrammerZamanNow
