### ISSUE TITLE
Validation di frontend, backend, atau keduanya?

### ISSUE THREAD

**Issue by rasyidev** [ProgrammerZamanNow/qna#125]
Saat membuat aplikasi web, mobile atau desktop kita sering mengimplementasikan proses input data ke dalam database. Data tidak serta merta masuk ke dalam database, melainkan divalidasi terlebih dahulu. _Best practice_ untuk membuat _validation_ ini sebaiknya di bagian frontend, backend atau keduanya ya, Pak?
Terima kasih sebelumnya

**Comment by kingrootid** [comment]
Menurut saya sih lebih baik kedua nya 

tapi pernah ada kasus seperti ini, coba terapin di backend ya ngga ada issue lain

**Comment by rasyidev** [comment]
Siap kang, sebenernya saya juga sependapat. Saya pernah ngerjain project fullstack CRUD. Di backend dibuat validation, di frontend juga dibuat validation. Tapi itu ngerjainnya jadi tambah lama kalo data yg diinput banyak `field` nya. Saya penasaran best practice nya di dunia industri seperti apa, hehe.

**Comment by kingrootid** [comment]
kalau saya kemarin pake joi 
enak, mudah dipahami,

**Comment by AaEzha** [comment]
> Siap kang, sebenernya saya juga sependapat. Saya pernah ngerjain project fullstack CRUD. Di backend dibuat validation, di frontend juga dibuat validation. Tapi itu ngerjainnya jadi tambah lama kalo data yg diinput banyak `field` nya. Saya penasaran best practice nya di dunia industri seperti apa, hehe.

Kalau BE dan FE adalah dua orang berbeda, jelas bukan menjadi issue di sini.

**Comment by rasyidev** [comment]
> kalau saya kemarin pake joi enak, mudah dipahami,

joi tuh ORM gitu ya bang?

**Comment by rasyidev** [comment]
> > Siap kang, sebenernya saya juga sependapat. Saya pernah ngerjain project fullstack CRUD. Di backend dibuat validation, di frontend juga dibuat validation. Tapi itu ngerjainnya jadi tambah lama kalo data yg diinput banyak `field` nya. Saya penasaran best practice nya di dunia industri seperti apa, hehe.
> 
> Kalau BE dan FE adalah dua orang berbeda, jelas bukan menjadi issue di sini.

Nah masalahnya ini ngerjainnya sendiri sih bang. Fullstack, wkkw

**Comment by kingrootid** [comment]
> > kalau saya kemarin pake joi enak, mudah dipahami,
> 
> joi tuh ORM gitu ya bang?

bukan joi itu validator
orm kaya sequelize, typeorm dll gitu

**Comment by rasyidev** [comment]
> > > kalau saya kemarin pake joi enak, mudah dipahami,
> > 
> > 
> > joi tuh ORM gitu ya bang?
> 
> bukan joi itu validator orm kaya sequelize, typeorm dll gitu

I see. Makasih bang Insightnya

**Comment by mushlih-almubarak** [comment]
Kalau menurut saya sih di keduanya, atau paling minimal di backendnya

**Comment by rasyidev** [comment]
> 

Siap, makasih Insightnya bang

**Comment by mushlih-almubarak** [comment]
Yup. Sama"

**Comment by khannedy** [comment]
https://www.youtube.com/watch?v=sAiU2fc2qWY&ab_channel=ProgrammerZamanNow
