### ISSUE TITLE
Roadmap Backend Developer

### ISSUE THREAD

**Issue by rangga98** [ProgrammerZamanNow/qna#127]
Halo bang, izin bertanya. Jika ingin menjadi seorang Backend Developer, dari pemula sampai mahir, awal nya harus belajar apa dulu dan item item apa saja yang perlu dikuasai ya?. Terima kasih

**Comment by kingrootid** [comment]
bisa cek disini
https://roadmap.sh/backend

**Comment by rangga98** [comment]
> bisa cek disini
> https://roadmap.sh/backend

Thank u gan

**Comment by iqlal** [comment]
@rangga98 
Tolong di close bang
