### ISSUE TITLE
Kalo build aplikasi, lebih baik build Back-end dulu atau Front-end dulu ?

### ISSUE THREAD

**Issue by angganix** [ProgrammerZamanNow/qna#129]
Saya suka galau kalau pas mau buat aplikasi, apakah buat struktur API nya dulu dari back-end baru front-end nya, atau saya buat dulu mock-up tampilan front-end nya baru back-end.

**Comment by AaEzha** [comment]
Jawaban paling ideal adalah membuat SRS (Software Requirements Specification).

IMHO.

**Comment by angganix** [comment]
> Jawaban paling ideal adalah membuat SRS (Software Requirements Specification).
> 
> IMHO.

requirement, spec, API documentation sudah ready. sebagai single fighter tanpa tim. suka galau mau ngerjain back-end dulu atau front-end dulu... blue print, design dsb. nya udah ready...

**Comment by mushlih-almubarak** [comment]
Kalau saya sih biasanya front endnya dulu, jadi data"nya masih statis dulu. Trus setelah tampilannya sudah jadi baru data"nya diubah ke dinamis pakai backend

**Comment by zycoder142** [comment]
Kalo design nya sudah ready harus nya udah enak sih.. masalah mana yang mau di kerjain dulu itu optional yg penting dah ada gambaran fitur yg mau dibuat

**Comment by fakhrulnugroho** [comment]
https://youtu.be/3PMLwe_C-F0

sudah di bahas di youtube nya pak Eko

**Comment by khannedy** [comment]
https://youtu.be/wtYSFNJE3h8
