### ISSUE TITLE
Selain bahasa pemrograman dan framework, apa saja yang harus dipelajari untuk menjadi backend developer yang baik?

### ISSUE THREAD

**Issue by solahkay** [ProgrammerZamanNow/qna#14]
Saya masih merasa bingung apa saja yang harus dipelajari untuk menjadi backend developer yang baik selain bahasa pemrograman dan framework, kang.

**Comment by KNobHack** [comment]
Izin berpendapat. Sepengalaman saya menguasai bahasa pemrograman dan framework sangat penting. Tapi lebih penting lagi menguasai teori algoritma dan struktur data, dan mengetahui permasalahan umum dan solusinya. Akan mempercepat dan mengefisienkan penyelesaian project.

**Comment by dinanrm** [comment]
> Izin berpendapat. Sepengalaman saya menguasai bahasa pemrograman dan framework sangat penting. Tapi lebih penting lagi menguasai teori algoritma dan struktur data, dan mengetahui permasalahan umum dan solusinya. Akan mempercepat dan mengefisienkan penyelesaian project.

Setuju ☝🏻
Izin menambahkan juga, bisa coba pelajari hal-hal seperti Software Architecture, Design Pattern & Coding Principles (SOLID, KISS, DRY, YAGNI, dll). Hal-hal fundamental seperti ini yang biasanya orang-orang lewatkan. Padahal cukup vital sebetulnya, khususnya bagi kita-kita yang berposisi sebagai backend.

Dengan code & arsitektur yang baik tentunya aplikasi backend yang kita buat akan semakin handal dan efisien untuk digunakan.

**Comment by dinanrm** [comment]
> Izin berpendapat. Sepengalaman saya menguasai bahasa pemrograman dan framework sangat penting. Tapi lebih penting lagi menguasai teori algoritma dan struktur data, dan mengetahui permasalahan umum dan solusinya. Akan mempercepat dan mengefisienkan penyelesaian project.

Setuju ☝🏻
Izin menambahkan juga ya mas @skaysans, bisa coba pelajari hal-hal seperti Software Architecture, Design Pattern & Coding Principles (SOLID, KISS, DRY, YAGNI, dll). Hal-hal fundamental seperti ini yang biasanya orang-orang lewatkan. Padahal cukup vital sebetulnya, khususnya bagi kita-kita yang berposisi sebagai backend.

Dengan code & arsitektur yang baik tentunya aplikasi backend yang kita buat akan semakin handal dan efisien untuk digunakan.

**Comment by khannedy** [comment]
1. basic computer, menginstall app, menginstall os
2. basic terminal, bikin folder, baca file, pindah folder
3. algoritma dan pemrograman dasar
4. pemrograman lanjutan, oop
5. struktur data
6. io programming, io file, io network
7. database relational
8. advanced programming, thread, concurrency, goroutine, koroutine, parallel programming
9. framework 
10. code design, code quality , clean code, refactoring, design patterns
11. database non relational, redis, elasticsearch, mongodb, cassandra
12. system design, microservices, integration patterns, event driven, cloud native, 
13. framework lanjutan
14. bebas
