### ISSUE TITLE
Pak, saya sebagai pemula terkadang bingung menyusun folder sebuah aplikasi.. Susunan yang saya tau cuman mvc aja. Ini ada ilmunya ga sih pak? kalau ada saya ingin tau apa keywordnya dan pengen saya pelajari.. Terima kasih

### ISSUE THREAD

**Issue by FadhliAbrar** [ProgrammerZamanNow/qna#147]

**Comment by FadhliAbrar** [comment]
Udah tau sekarang jawabanya pak, masuk ke clean code atau clean architecture ternyata.. namun kalau saya keliru atau ada tambahan mohon kasih tau

**Comment by agung-ap** [comment]
Kalau mau lebih deep dive lagi coba pelajari SOA (service oriented architecture)

**Comment by khannedy** [comment]
https://youtu.be/tu6IKx_VXLA
