### ISSUE TITLE
tertarik belajar data scientist tapi masih bingung

### ISSUE THREAD

**Issue by eca24kd** [ProgrammerZamanNow/qna#15]
hallo pak, saya belakangan ini tertarik dengan profesi data scientist. saya juga sudah melihat tentang python di channel pak Eko. kira-kira apa lagi yang harus saya siapkan? saya juga masih bingung mengenai tentang apa yang dikerjakan oleh data scientist sih hehe
TIA

**Comment by khannedy** [comment]
kita bahas sama nara sumber yang udah jadi DS
