### ISSUE TITLE
baikah menyimpan file (foto) di database dalam bentuk base64

### ISSUE THREAD

**Issue by arfian-rp** [ProgrammerZamanNow/qna#152]
halo selamat malam. saya ingin bertanya apa baik menyimpan file (foto) dalam bentuk string base64?
apakh mempengaruhi ukuran database atau bagaimana?
terimakasih

**Comment by iqlal** [comment]
kenapa nggak disimpan di object storage / blob storage ???

**Comment by gufronnakaaw** [comment]
kenapa ga url namanya aja yang disimpen ke database? jadi biarin file nya disimpen server

**Comment by gufronnakaaw** [comment]
kenapa ga url namanya aja yang disimpen ke database? jadi biarin file nya disimpen server

**Comment by iqlal** [comment]
> kenapa ga url namanya aja yang disimpen ke database? jadi biarin file nya disimpen server

Kalau menurut saya kalau gini gak efisien bang

**Comment by binsarjr** [comment]
> kenapa nggak disimpan di object storage / blob storage ???

Setuju dengan ini atau lebih bagusnya lagi pake s3 storage

**Comment by iqlal** [comment]
@khannedy 

UP !
