### ISSUE TITLE
Penting gak si nguasain biner, oktal dan hexadesimal?

### ISSUE THREAD

**Issue by AldiMlna** [ProgrammerZamanNow/qna#162]
Permisi pak eko & senior yang sekiranya baca issue ini? Mau tanya. Sebenarnya penting gak si kita pelajarin bilangan diatas dalam dunia programing? Sering kepake gak si kalo kita lagi ngoding? Boleh minta contoh kasus penggunaan nya gak baik itu dalam programing dan diluar programing?

Terima kasih

**Comment by iqlal** [comment]
Halo @AldiMlna

Menurut saya penting bagi orang yang ingin kuasai low level, tapi boleh juga lah dipelajari sama programmer umum...

**Comment by ryval-samuel777** [comment]
halo @AldiMlna 

Menurut saya
-  Jika BARU mulai belajar ngoding. cukup cari tau saja penggunaannya dari bilangan-bilangan diatas atau dihiraukan saja dulu itu. Tapi kalau mau di pelajari lebih dalam silahkan, tinggal di googling saja. 

- penggunaannya untuk ngoding, yang saya sering lihat itu hexadesimal. Biasanya dipakai untuk penggunaan warna cth #FFFFFF untuk warna putih.

- penggunaan dalam programming 
  + penentuan warna (menggunakan hexadecimal)

- diluar programming 
  + pengalamatan pada jaringan komputer (menggunakan hexadecimal dan biner)

mungkin jika ada yang lebih tau kegunaannya bisa ditambahkan lagi hehe

**Comment by iqlal** [comment]
> halo @AldiMlna
> 
> Menurut saya
> 
> * Jika BARU mulai belajar ngoding. cukup cari tau saja penggunaannya dari bilangan-bilangan diatas atau dihiraukan saja dulu itu. Tapi kalau mau di pelajari lebih dalam silahkan, tinggal di googling saja.
> * penggunaannya untuk ngoding, yang saya sering lihat itu hexadesimal. Biasanya dipakai untuk penggunaan warna cth #FFFFFF untuk warna putih.
> * penggunaan dalam programming
>   
>   * penentuan warna (menggunakan hexadecimal)
> * diluar programming
>   
>   * pengalamatan pada jaringan komputer (menggunakan hexadecimal dan biner)
> 
> mungkin jika ada yang lebih tau kegunaannya bisa ditambahkan lagi hehe

YAP BETUL MAS @ryval-samuel777 

Bagi saya juga berguna banget karena berkecimpung di Network dan Security

**Comment by localhousee** [comment]
> halo @AldiMlna
> 
> Menurut saya
> 
>     * Jika BARU mulai belajar ngoding. cukup cari tau saja penggunaannya dari bilangan-bilangan diatas atau dihiraukan saja dulu itu. Tapi kalau mau di pelajari lebih dalam silahkan, tinggal di googling saja.
> 
>     * penggunaannya untuk ngoding, yang saya sering lihat itu hexadesimal. Biasanya dipakai untuk penggunaan warna cth #FFFFFF untuk warna putih.
> 
>     * penggunaan dalam programming
>       
>       * penentuan warna (menggunakan hexadecimal)
> 
>     * diluar programming
>       
>       * pengalamatan pada jaringan komputer (menggunakan hexadecimal dan biner)
> 
> 
> mungkin jika ada yang lebih tau kegunaannya bisa ditambahkan lagi hehe

mau nambahain, kalo octal mungkin jarang di programming, real casenya ada di UNIX, misal atur permission (chmod blabla). lagian karna sizenya cuma 8 bit dan komputer jaman sekarang architecturenya udah 32 ama 64 bit jadi yg kepake base16 alias hexadecimal.

**Comment by iqlal** [comment]
so @AldiMlna udah answered ya...
jangan lupa di close ✅
