### ISSUE TITLE
Kenapa one to one relationship perlu dipisah ditable yang berbeda?

### ISSUE THREAD

**Issue by rezamukti** [ProgrammerZamanNow/qna#163]
Mas Eko
Kenapa one to one relationship rdbms perlu dipisah ditable yang berbeda?

Kapan one to one relationship digabung menjadi satu tabel kapan saatnya dipisah?

**Comment by rafiseptian90** [comment]
Izin menjawab, menurut opini saya kenapa harus dipisah **agar struktur pada tabel sesuai dengan tujuan tabel itu sendiri dibuat**. Saya suka memisahkan antara tabel _users_ dengan tabel _profiles_, mengapa saya memilih untuk memisahkan tabel _users_ dan tabel _profiles_ ?, karena saya berasumsi tabel _users_ itu khusus untuk _credentials authentication_ (username, password, email, dll), sementara tabel _profiles_ untuk menyimpan data dari users tersebut (name, gender, birth_date, address, dll). Sebenarnya bisa saja mereka digabungkan menjadi satu tabel, tetapi menurut saya itu menjadikan tabel users menjadi tidak sesuai dengan tujuannya. Jadi kesimpulannya saya memilih untuk memisahkan menjadi dua tabel

**Comment by radenfajrus** [comment]
Izin menjawab, setuju dgn @rafiseptian90, tergantung tujuan pembuatan.

Misalnya awalnya diminta membuat aplikasi hrd, ttg penggajian, manajemen dokumen kontrak, dll. Kemudian dibikin itu jadi satu aplikasi dengan tabel usernya.
Eh tiba2 ada kebutuhan membuat tambahan fitur manajemen proyek (kyk jira). akhirnya table user di alter untuk nambah beberapa kolom. Ternyata beberapa bulan kemudian, fiturnya gk jadi dipake. Mau rollback git, gk bisa. Mau alter kolom, takut error. Mungkin kalau tablenya dipisah bisa lebih mudah untuk di delete (**opini saya**). karena tujuan pembuatannya untuk suatu fitur. kl fiturnya gk dipake, tablenya gk dipake.

**Comment by khannedy** [comment]
https://www.youtube.com/watch?v=6xU8K_w7gN4&ab_channel=ProgrammerZamanNow

**Comment by narwinoks** [comment]
apakah nanti nya pengaruh ke peformarce jika terlalu banyak join ketika mengambil data ?
