### ISSUE TITLE
kapan waktu yg tepat penggunaan pointer?

### ISSUE THREAD

**Issue by arfian-rp** [ProgrammerZamanNow/qna#164]
permisi ijin bertanya, saya merasa kebingungan kapan dan saat yg tepat menggunakan pointer sebagai parameter di function?

**Comment by adhikag24** [comment]
Izin menjawab mas, mungkin banyak case untuk menggunakan pointer sebagai parameter di sebuah function, tapi saya coba saya share yang saya tau.

Biasanya menggunakan pointer sebagai paramater / return di sebuah function **ketika data yang ingin di kembalikan / di terima bisa berupa null**, jadi karna data type biasa itu tidak bisa menerima data null, kita bisa menggunakan pointer.

misal ada function untuk mengambil data dari database, dan kita ingin mengembalikan null jika datanya tidak ditemukan, dalam case ini kita bisa pakai pointer untuk return / balikan dari function tersebut.

**Comment by arfian-rp** [comment]
> Izin menjawab mas, mungkin banyak case untuk menggunakan pointer sebagai parameter di sebuah function, tapi saya coba saya share yang saya tau.
> 
> Biasanya menggunakan pointer sebagai paramater / return di sebuah function **ketika data yang ingin di kembalikan / di terima bisa berupa null**, jadi karna data type biasa itu tidak bisa menerima data null, kita bisa menggunakan pointer.
> 
> misal ada function untuk mengambil data dari database, dan kita ingin mengembalikan null jika datanya tidak ditemukan, dalam case ini kita bisa pakai pointer untuk return / balikan dari function tersebut.

thanks mas

**Comment by hal8888** [comment]
izin nambahin:

>permisi ijin bertanya, saya merasa kebingungan kapan dan saat yg tepat menggunakan pointer sebagai parameter di function?

pake pointer di function parameter juga sebagai cara supaya data yang mau kita modify gak escape ke heap memory.

**Comment by thoriqadillah** [comment]
izin nambahin:
mungkin kalo bicara pointer itu harus tau dulu pass by value dan pass by reference. Kalo bicara di bahasa yang ada garbage collection yang gaada fitur pointernya kaya java, js, php, dll, pass by value itu dia biasanya akan berlaku buat tipe data primitive kaya `number`, `integer`, `boolean`, `string` (kecuali string di java, `String` di java itu object), dll. Kalo pass by reference itu berlaku buat object, kaya class (di js, java, php, dll), js object, dll.

Pass by value itu, kaya gini
```ts
let a = 0
function modify(n: number): number {
  n = n + 1
  return  n
}

const b = modify(a)

console.log(a) // 0
console.log(b) // 1
```
Ketika pass by value, original value nya gak bakal berubah meskipun kamu modify di dalam suatu function. Beda cerita kalo pass by reference, Kalo pass by reference, original value nya ketika di pass ke suatu function misalnya, original value itu bakal ikut keganti juga

```ts
interface T {
    n: number
}

let a: T = {
    n: 0
}

function modify(t: T): T {
  t.n = t.n + 1
  return  t
}

const b = modify(a)

console.log(a.n) // 1
console.log(b.n) // 1
```

Terus hubungannya sama pointer apa dong? Hubungannya, kalo pake pointer itu lebih bisa ngontrol kita mau apain itu valuenya. Kalo pass dengan pointer, berarti kita pass by reference, jadi original valuenya bakal ikut berubah kalo di tempat lain diubah. Kalo pake non pointer, berarti pass by value, jadi original valuenya itu gak berubah ketika di tempat lain diubah, jadinya dia di copy value nya
