### ISSUE TITLE
Bagaimana project itu harusnya dibangun ?

### ISSUE THREAD

**Issue by febrarisupaldi** [ProgrammerZamanNow/qna#17]
Sebenarnya tahap-tahap yang baik untuk membangun sebuah program itu seperti apa pak ?

Apakah harus dibuat dulu untuk dokumentasi nya ? Terus unit testnya baru mulai coding program utama nya ? terus databasenya apakah disiapkan lebih dahulu atau sejalannya saja ? mohon pak dibahas bagaimana program itu seharusnya dibangun tapi dengan cara yang tepat, Terima kasih

**Comment by dzawata** [comment]
Up

Terutama dengan kondisi komposisi tim yang belum ideal.

**Comment by CakraDarma** [comment]
Up 
mungkin bisa berbagi pengalmannya

**Comment by agus24** [comment]
Kalo gw unit test sama db berjalan aja. Misal mao buat modul payment. Biasa gw bagi2 dl kebutuhannya cth ad thirdparty, perlu redis / mq apa ngk. Setupnya 1 per 1. Trus masuk ke code (include db / migration) trus unit baru code

**Comment by dinanrm** [comment]
Bisa coba tonton video ini mas @febrarisupaldi : https://youtu.be/3PMLwe_C-F0
Sudah pernah dibuat sama mas Eko waktu itu.
