### ISSUE TITLE
Menangani multi language dalam database

### ISSUE THREAD

**Issue by momogie** [ProgrammerZamanNow/qna#173]
Halo, 
dulu pernah ada pertanyaan tentang bagaimana menangani datetime, timezone. 
nah sekarang saya ijin bertanya bagaimana best practice nya untuk menangani multi language untuk data dalam database, terimakasih

**Comment by Veelio96** [comment]
Saya coba jawab ya,

1. Pelajarin konsep Internalization atau I18n, harusnya di channel YouTube ProgrammerZamanNow sudah ada pembahasannya. Bisa coba dicheck terlebih dahulu
2. Pastikan data yang ingin ditanganin tidak multitafsir / banyak arti.
3. Field data yang ada di database kalau bisa disimpan mengunakan Enumerations / unique constant code, supaya mempermudah proses penerjemahaan di resource bundlenya.

silakan jawabannya diperbaiki ataupun ditambah apabila dirasa jawabanya yang saya kasih ini tidak sesuai.

Terima kasih.

**Comment by khannedy** [comment]
https://youtu.be/dx0ibv_hct8
