### ISSUE TITLE
Cara kalkulasi resource server untuk kebutuhan aplikasi

### ISSUE THREAD

**Issue by aliffirdi** [ProgrammerZamanNow/qna#178]
Apakah ada aplikasi kalkulator resource yang dapat digunakan untuk menghitung sumberdaya server yang dibutuhkan berdasarkan aplikasi yang kita buat?

**Comment by prabowomurti** [comment]
Menarique. Setahu saya kalau di Google Cloud Platform, untuk tiap resource yang terlalu tinggi / besar, dia ada rekomendasi untuk mematikan / disable. Kalau terlalu rendah, service sering mati dan bermasalah. Tapi kalau sedari awal sudah dihitung, saya belum ketemu.

**Comment by khannedy** [comment]
https://youtu.be/g0DXyEAqOko

**Comment by aliffirdi** [comment]
thank's kang eko, helpful buat belajar skalabilitas server :)
