### ISSUE TITLE
Lebih Baik Full-stack atau Specialist?

### ISSUE THREAD

**Issue by azmifauzy** [ProgrammerZamanNow/qna#18]

**Comment by zuramai** [comment]
Bantu jawab, why not both? lebih baik full-specialist.
![image](https://user-images.githubusercontent.com/45036724/165182398-0574e405-a3af-49a0-afa9-b9aaf8c075b2.png)

**Comment by renomureza** [comment]
Jawaban: 

[![Watch the video](https://img.youtube.com/vi/Cn5fLJIR2Vo/maxresdefault.jpg)](https://www.youtube.com/watch?v=Cn5fLJIR2Vo)
