### ISSUE TITLE
kenapa untuk recruter jarang menginginkan programmer dari bahasa lain? 

### ISSUE THREAD

**Issue by bhumong** [ProgrammerZamanNow/qna#187]

**Comment by imamxxl** [comment]
Kalo boleh saya ikut berpendapat, simpel aja sih mas. Recruiter gak ingin ribet-ribet nanti setelah ngehire orang baru tapi mesti harus diajarin lagi ilmu baru lagi. meskipun seandainya sama konsep OOP nya tapi untuk penyesuaian bahasa baru nantikan gak mudah. Mending cari yang sesuai requirements aja

**Comment by bhumong** [comment]
setujut sih sama mas @imamxxl, permasalahan utama nya adalah programmer jadi terjebak dalam suatu ekosistem bahasa tertentu, setelah di coba dipelajari kadang tidak jauh berbeda
