### ISSUE TITLE
Kapan video microservice dilanjut?

### ISSUE THREAD

**Issue by KNobHack** [ProgrammerZamanNow/qna#19]
Video microservice pak eko yang sebelumnya membuat saya tertarik dan paham teori dasar tentang microservice, saya ucapkan banyak terimakasih pak, tapi playlist video nya seperti berhenti di tengah jalan. Kira kira kapan ya pak untuk bisa lanjut video microservice nya?

**Comment by khannedy** [comment]
nanti akan di buat ulang
