### ISSUE TITLE
Perlukah portfolio bagi seorang DevOps Engineer?

### ISSUE THREAD

**Issue by Script47ph** [ProgrammerZamanNow/qna#2]
Izin bertanya Mas Eko, bagi seseorang yang ingin berkarir dalam bidang DevOps apakah perlu ada yang namanya portfolio project seperti seorang programmer? 
Kemudian bagaimana caranya kita memperlihatkan skill yang kita kuasai ke publik tanpa melalui portfolio project seperti seorang programmer jika memang portfolio project tidak diperlukan bagi seorang DevOps Engineer?

**Comment by abidulfikri28** [comment]
Ikut nanya ini juga mas

**Comment by iqlal** [comment]
@Script47ph Bantu jawab mas,

Mungkin kalau DevOps kita bisa show off sertifikasi professional (Cloud, K8s, dll) dan juga project yang sudah kita kerjakan

**Comment by khannedy** [comment]
sudah dijawab di youtube

**Comment by Script47ph** [comment]
Terima kasih Mas atas jawabannya @iqlal @khannedy
