### ISSUE TITLE
Bagaimana cara kerja aplikasi real time?

### ISSUE THREAD

**Issue by Akmal-Keisin** [ProgrammerZamanNow/qna#200]
Biasanya waktu saya membuat web/api memerlukan refresh pada halaman web untuk melihat/update pada data baru. Kira kira bagaimana cara kerja suatu web/aplikasi real time yang tidak memerlukan refresh seperti itu?

**Comment by Akmal-Keisin** [comment]
Biasanya waktu saya membuat web/api memerlukan refresh pada halaman web untuk melihat/update pada data baru. Kira kira bagaimana cara kerja suatu web/aplikasi real time yang tidak memerlukan refresh seperti itu?

**Comment by wahitfitriyanto** [comment]
Saya bantu jawab sedikit,  aplikasi realtime memproses data saat diterima. Aplikasi ini biasanya memproses data menurut batasan waktu tertentu (misal, setiap menit atau setiap jam)

Aplikasi realtime sering berfungsi dalam pengaturan di mana terdapat kemampuan otomatisasi. Jenis ini umumnya lebih dapat diprediksi daripada aplikasi tradisional karena perbandingan kesalahannya lebih sedikit dibandingkan dengan aplikasi tradisional. Fungsi realtime memiliki window of time yang lebih kecil untuk memperbaiki kesalahan, dan konsekuensinya bisa lebih parah.

Agar lebih jelas, saya berikan beberapa "syarat" dari pembuatan aplikasi realtime. Aplikasi yang beroperasi secara real time harus mengintegrasikan data dalam jumlah besar dengan cepat dan akurat. Aplikasi ini harus mempertahankan kecepatan pemrosesan waktu nyata dan kekuatan unit pemrosesan pusat tanpa latensi atau delay. Aplikasi ini harus merespon dengan cepat terhadap perubahan data untuk memberikan hasil yang tepat waktu dan memastikan interaksi yang lancar dengan user. 

Beban kerja data realtime sering berubah-ubah, dan itu merupakan sifat aliran data. Aplikasi harus dapat memperluas dan mengontrak kemampuannya untuk memenuhi permintaan yang berubah. Aplikasi realtime harus menangani kegagalan dengan baik sehingga keseluruhan sistem terus beroperasi bahkan ketika komponen individual gagal. Kegagalan akan terjadi saat pembaruan aplikasi dibuat dan karena persyaratan kinerja berfluktuasi dengan traffic volume.

**Comment by localhousee** [comment]
Kalau ranahnya web, biasanya pakai websocket, cara kerjanya gimana? https://www.rfc-editor.org/rfc/rfc6455

dijabarin mulai pengenalan sampai contoh websocket itu gimana

**Comment by khannedy** [comment]
https://youtu.be/w_rOM943vCw
