### ISSUE TITLE
Boleh ga sih 1 Instance di jadikan server untuk banyak Aplikasi?

### ISSUE THREAD

**Issue by budimanr3101** [ProgrammerZamanNow/qna#206]
Pagi mas Eko, mau nya doong.... kira2 bagus ga sih 1 instance di jadikan untuk server banyak aplikasi?
apa Pros dan Cons nya?

**Comment by iqlal** [comment]
Bantu jawab ya Mas @budimanr3101 

Pros-nya mungkin jelas lebih hemat ya...
Cons-nya seringnya sulit termanage dan misal instance / VM tersebut bermasalah semua aplikasi tersebut bermasalah

**Comment by fakhrulnugroho** [comment]
https://youtu.be/JaO_SVfVBgs

udah di bahas di channel youtube Programmer Zaman Now

**Comment by budimanr3101** [comment]
Waah iyah udah pernah di bahas... Thanks...
