### ISSUE TITLE
Trunk Based Development atau Git Flow?

### ISSUE THREAD

**Issue by jackyrusly** [ProgrammerZamanNow/qna#213]
Halo mas Eko, Izin bertanya, mending pakai TBD atau Git Flow ya mas?

Kalau TBD, Apakah fitur2 yang belum ready to release di merge juga ke branch master (trunk) tapi bisa di toggle feature flagnya atau bagaimana ya mas?

Terimakasih mas Eko

**Comment by khannedy** [comment]
https://youtu.be/jydxcnSOIG4
