### ISSUE TITLE
Jalur Belajar Mobile yang benar itu gimana?

### ISSUE THREAD

**Issue by agusdwimilniadi** [ProgrammerZamanNow/qna#234]
Saya selama kurang lebih 3 tahun sudah bergelut di dunia website, dan saya pengen belajar hal baru yaitu Mobile. Pertanyaan nya, saat saya belajar mobile itu kira2 bisa dimulai belajar dari mana ya? Saya bingung memilih antara 

1. React Native
2. Swift
3. Dart (Flutter)
4. Kotlin
5. Java

Kalau dari saran temen2, mending belajar apa dan mulai dari mana? Terimakasih

**Comment by BobChrismansyah** [comment]
Izin menjawab
***
Yang perlu diketahui dalam mobile dev itu:
1. Native Apps
	Hanya berjalan di satu sistem operasi.
              Android Development = Java atau Kotlin
              IOS Development = Swift atau Objective-C

2. Cross Platform Apps
	Berjalan lebih dari dua sistem operasi, bisa menggunakan Flutter (Dart) atau React Native (JavaScript).

3. Hybrid Apps
	Berjalan lebih dari dua sistem operasi tapi berbasis website, bisa menggunakan Xamarin, ionic & Apache Cordova.
***

> sebelum membuat app mobile tentukan dulu akan berjalan pada sistem operasi mana.

Saran saya tool yang cocok untuk mulai belajar mobile bisa menggunakan **[Android Studio](https://developer.android.com/studio)** (Java)

**Comment by agusdwimilniadi** [comment]
> Izin menjawab
> 
> Yang perlu diketahui dalam mobile dev itu:
> 
> 1. Native Apps
>    Hanya berjalan di satu sistem operasi.
>    Android Development = Java atau Kotlin
>    IOS Development = Swift atau Objective-C
> 2. Cross Platform Apps
>    Berjalan lebih dari dua sistem operasi, bisa menggunakan Flutter (Dart) atau React Native (JavaScript).
> 3. Hybrid Apps
>    Berjalan lebih dari dua sistem operasi tapi berbasis website, bisa menggunakan Xamarin, ionic & Apache Cordova.
> 
> > sebelum membuat app mobile tentukan dulu akan berjalan pada sistem operasi mana.
> 
> Saran saya tool yang cocok untuk mulai belajar mobile bisa menggunakan **[Android Studio](https://developer.android.com/studio)** (Java)

Kenapa kok tidak labfsyng ke Cross Platform Apps? Apa alasan nya?

**Comment by MashudiSudonym** [comment]
boleh saja

> > Izin menjawab
> > Yang perlu diketahui dalam mobile dev itu:
> > 
> > 1. Native Apps
> >    Hanya berjalan di satu sistem operasi.
> >    Android Development = Java atau Kotlin
> >    IOS Development = Swift atau Objective-C
> > 2. Cross Platform Apps
> >    Berjalan lebih dari dua sistem operasi, bisa menggunakan Flutter (Dart) atau React Native (JavaScript).
> > 3. Hybrid Apps
> >    Berjalan lebih dari dua sistem operasi tapi berbasis website, bisa menggunakan Xamarin, ionic & Apache Cordova.
> > 
> > > sebelum membuat app mobile tentukan dulu akan berjalan pada sistem operasi mana.
> > 
> > 
> > Saran saya tool yang cocok untuk mulai belajar mobile bisa menggunakan **[Android Studio](https://developer.android.com/studio)** (Java)
> 
> Kenapa kok tidak langsung ke Cross Platform Apps? Apa alasan nya?

kalau saya anggap cros platform itu sama seperti hybrid

kenapa ga dianjurkan langsung ke hybrid, karena anda akan ketemu dengan kasus-kasus dimana diharuskan menggunakan "API" dari native tiap komponen di device, misal camera ...

dengan tau seluk beluk native lebih dahulu, anda akan dapat menangani dengan baik jika ada masalah saat development yang bersinggunggan dengan komponen native.

**Comment by agusdwimilniadi** [comment]
> boleh saja
> 
> > > Izin menjawab
> > > Yang perlu diketahui dalam mobile dev itu:
> > > 
> > > 1. Native Apps
> > >    Hanya berjalan di satu sistem operasi.
> > >    Android Development = Java atau Kotlin
> > >    IOS Development = Swift atau Objective-C
> > > 2. Cross Platform Apps
> > >    Berjalan lebih dari dua sistem operasi, bisa menggunakan Flutter (Dart) atau React Native (JavaScript).
> > > 3. Hybrid Apps
> > >    Berjalan lebih dari dua sistem operasi tapi berbasis website, bisa menggunakan Xamarin, ionic & Apache Cordova.
> > > 
> > > > sebelum membuat app mobile tentukan dulu akan berjalan pada sistem operasi mana.
> > > 
> > > 
> > > Saran saya tool yang cocok untuk mulai belajar mobile bisa menggunakan **[Android Studio](https://developer.android.com/studio)** (Java)
> > 
> > 
> > Kenapa kok tidak langsung ke Cross Platform Apps? Apa alasan nya?
> 
> kalau saya anggap cros platform itu sama seperti hybrid
> 
> kenapa ga dianjurkan langsung ke hybrid, karena anda akan ketemu dengan kasus-kasus dimana diharuskan menggunakan "API" dari native tiap komponen di device, misal camera ...
> 
> dengan tau seluk beluk native lebih dahulu, anda akan dapat menangani dengan baik jika ada masalah saat development yang bersinggunggan dengan komponen native.

Terimakasih sudah menjawab
