### ISSUE TITLE
Gak hafal sytanx

### ISSUE THREAD

**Issue by AvinFajarF** [ProgrammerZamanNow/qna#241]
Saya gak hafal semua sytanx coding hanya sebagian saja yang saya hafal  , apakah saya bisa menjadi Programmer yang profesional?

**Comment by nadirelc** [comment]
menurut mas hilman sekolah koding ngga masalah mas https://www.instagram.com/reel/Ch1H5lxMPUY/?utm_source=ig_web_copy_link

**Comment by AvinFajarF** [comment]
> 

Oke thanks infonya

**Comment by AvinFajarF** [comment]
.

**Comment by ahanafi** [comment]
@AvinFajarF izin bantu jawab gan, dulu ane juga pas SMK ga hafal2 syntaxnya, bahkan ane sampe tanya ke guru sama kaka kelas yg emg jago di programming. Pas ane tanya, katanya ga usah dihafal, yang penting banykin **jam terbang** aja, kaya sering belajar coba, misal kita lagi belajar basic php, nah kita step berikutnya kita coba implement ke studi kasus tertentu. Makin banyak coba-coba, makin banyak baca, nanti otomatis tanpa ngehafalin syntax pun kita akan hafal dengan sendirinya.

Ane ngerasain sendiri gan wkwkwk, cuma sharing aja ya.. semoga terbantu.

**Comment by AvinFajarF** [comment]
> @AvinFajarF izin bantu jawab gan, dulu ane juga pas SMK ga hafal2 syntaxnya, bahkan ane sampe tanya ke guru sama kaka kelas yg emg jago di programming. Pas ane tanya, katanya ga usah dihafal, yang penting banykin **jam terbang** aja, kaya sering belajar coba, misal kita lagi belajar basic php, nah kita step berikutnya kita coba implement ke studi kasus tertentu. Makin banyak coba-coba, makin banyak baca, nanti otomatis tanpa ngehafalin syntax pun kita akan hafal dengan sendirinya.
> 
> Ane ngerasain sendiri gan wkwkwk, cuma sharing aja ya.. semoga terbantu.

Oke kan makasih atas infonya gan
