### ISSUE TITLE
apakah semua table harus ada dan menggunakan  created_at dan updated_at?

### ISSUE THREAD

**Issue by yakserr** [ProgrammerZamanNow/qna#246]
Apakah semua table harus ada dan menggunakan  created_at dan updated_at ?
jika iya apakah ada hal lain yang harus ditambahkan ? tidak hanya created_at dan updated_at.
atau kedua tabel tersebut hanya di parent tablenya saja seperti product(parent) dan product_categories(child) tidak perlu ?

Terimakasih :)

**Comment by hairullana** [comment]
Harus ada atau engga? Engga harus, tanpa ada itu juga masih bisa berjalan.
Fungsinya sesuai dengan nama fieldnya, biar tau kapan dibuat / diupdate nya, contoh kasusnya perusahaan mau cek aktif tidaknya user dengan updated_at tidak lebih dari 3 tahun terakhir
source: [Benefits of created_at or updated_at columns in database design](https://softwareengineering.stackexchange.com/questions/415517/benefits-of-created-at-or-updated-at-columns-in-database-design)

Kalau dari contoh kasus product & product_categories bisa diberikan keduanya, bisa salah satu, atau tidak keduanya, sesuaikan dengan kebutuhan aja. Kalau memang ga perlu, tidak usah biar mengurangi beban db

**Comment by yakserr** [comment]
> Harus ada atau engga? Engga harus, tanpa ada itu juga masih bisa berjalan. Fungsinya sesuai dengan nama fieldnya, biar tau kapan dibuat / diupdate nya, contoh kasusnya perusahaan mau cek aktif tidaknya user dengan updated_at tidak lebih dari 3 tahun terakhir source: [Benefits of created_at or updated_at columns in database design](https://softwareengineering.stackexchange.com/questions/415517/benefits-of-created-at-or-updated-at-columns-in-database-design)
> 
> Kalau dari contoh kasus product & product_categories bisa diberikan keduanya, bisa salah satu, atau tidak keduanya, sesuaikan dengan kebutuhan aja. Kalau memang ga perlu, tidak usah biar mengurangi beban db

okeii makasih mas jawabannya. mantap lengkap.
