### ISSUE TITLE
Pros dan cons menggunakan ORM dan tidak menggunakan ORM? 

### ISSUE THREAD

**Issue by fzn0x** [ProgrammerZamanNow/qna#259]
Halo mas Eko,

Sepertinya hal ini "dahulu" sering ditanyakan di komunitas IT, karena itu saya ingin bertanya tentang apa baik dan buruknya menggunakan ORM dan tidak menggunakan ORM. Karena selama ini, ORM dipandang sebagai suatu hal yang susah di-optimize jika yang kita ambil adalah perspektif dari pengguna ORM tersebut.

Saya iseng bertanya hal seperti ini karena mungkin ini bisa jadi pertanyaan yang menarik untuk menguatkan ilmu tentang database juga. 😄 (untuk nambah konten mas eko juga Hahahahahah #eh).

Terima kasih! #boom

**Comment by nandhasuhendra** [comment]
IMO,
Untuk penggunaan yg sederhana menggunakan ORM itu memang sangat membantu sekali yah. Tapi hal itu bisa jadi bom waktu ketika aplikasi semakin besar dengan relasi data yang kompleks, dan ketika tidak memiliki pemahaman yang baik dengan bagaimana ORM itu bekerja ketika mengenerate raw query yg akan di execute ke database. Dan ketika ada kebutuhan yg custom dan relate ke performance, raw query masih lebih baik

ini berdasarkan pengalaman saya yah hehe

**Comment by fzn0x** [comment]
> IMO, Untuk penggunaan yg sederhana menggunakan ORM itu memang sangat membantu sekali yah. Tapi hal itu bisa jadi bom waktu ketika aplikasi semakin besar dengan relasi data yang kompleks, dan ketika tidak memiliki pemahaman yang baik dengan bagaimana ORM itu bekerja ketika mengenerate raw query yg akan di execute ke database. Dan ketika ada kebutuhan yg custom dan relate ke performance, raw query masih lebih baik
> 
> ini berdasarkan pengalaman saya yah hehe

Terima kasih atas pendapatnya, mari kita menunggu bagaimana pendapat dari mas eko :D

**Comment by khannedy** [comment]
https://youtu.be/gb-H3g61Wfk
