### ISSUE TITLE
Playlist khusus perbedaan junior programmer dan senior programmer

### ISSUE THREAD

**Issue by rivalarya** [ProgrammerZamanNow/qna#26]
Pak, bikin playlist khusus buat bahas perbedaan Junior engineer dan senior engineer dong. Kayak misalnya kalo senior tuh nerapin clean code sedangkan Junior enggak, trus dijelain apa itu clean  code. Kayak gtu²🙏

**Comment by tedomasbro** [comment]
Iya mas eko dan coba tolong dijalaskan dong mas eko bagaimana caranya mendapatkan sebagi senior programmer dan junior programmer. Apakah diharuskan menguasi 1 bahasa dengan mahir atau ditentukan berdasarkan berapa lama dia bekerja sebagai programmer, atau seberapa lama dia bekerja di perushaan tersebut

**Comment by khannedy** [comment]
https://youtu.be/PRK7RBFJ-p8
