### ISSUE TITLE
perbadingan gaji di indonesia dan luar negri

### ISSUE THREAD

**Issue by IqbalFajri22** [ProgrammerZamanNow/qna#3]
Pak Eko izin bertanya. perbandingan gaji programmer di Indonesia sama di negara luar itu masih besaran mana?

**Comment by dinanrm** [comment]
Izin bantu jawab ya mas @IqbalFajri22.
Ada banyak sebetulnya sumber data salary dari hasil survey, tapi salah satu website yang cukup populer & sudah banyak yang voting di sana yaitu website Glassdoor.

Saya ambil salah satu profesi yang general nya ya, "Software Engineer" di Indonesia :
https://www.glassdoor.com/Salaries/indonesia-software-engineer-salary-SRCH_IL.0,9_IN113_KO10,27.htm

Nah kalo mau liat data salary yang dari luar, tinggal di ubah location ke negara lain.

**Comment by iqlal** [comment]
mhn di close mas @IqbalFajri22

**Comment by khannedy** [comment]
https://www.youtube.com/watch?v=F1LJGaAHE7g&ab_channel=ProgrammerZamanNow
