### ISSUE TITLE
Best Practice Mengembalikan Response API

### ISSUE THREAD

**Issue by AzzamyDev** [ProgrammerZamanNow/qna#301]
malam pak eko,

sebagai programer baru saya ingin tau best practice untuk mengebalikan Response API itu sperti apa,
beberapa pengalaman saya mengbalikan response itu berbeda2.

contoh 1 :
jika product yg di cari tidak ada .
status code : `404`
response body : 
```
{
"message" : "Produk tidak ditemukan"
}
```

contoh 2 :
jika product yg di cari tidak ada .
status code : `200`
response body : 
```
{
"status" : false
"message" : "Produk tidak ditemukan"
}
```

dari kedua cntoh di atas manakh yg relevan pak ?
atau adakah rule / aturan cara  untuk mengembalikan Response .

terimakasih

**Comment by khannedy** [comment]
https://youtu.be/QI-62smsi4A
