### ISSUE TITLE
Lanjutan dari kelas OPEN API apa ada kang?

### ISSUE THREAD

**Issue by ahmadihsanullah** [ProgrammerZamanNow/qna#308]
kang apa ada lanjutan video setelah kelas open api? dikarenakan saya masih bingung cara membuat restful api untuk web pribadi misalnya ataupun consume restful api website orang lain, terimakasih sebelumnya kang

**Comment by khannedy** [comment]
kelas open api sudah selesai

selanjutnya, silahkan belajar membuat API sesuai bahasa pemrograman yag digunakan
