### ISSUE TITLE
Hybrid atau Native? (Sekaligus curhat karir)

### ISSUE THREAD

**Issue by fityanrahman** [ProgrammerZamanNow/qna#317]
Izin bertanya, kang @khannedy dan semuanya. 

Saya seorang mobile programmer (saat ini flutter). Bagaimana prospek jenjang karir antara programmer hybrid dan native?

Saya bekerja kurleb selama 3 tahun di sebuah perusahaan berkembang. 1,5 tahun pertama, saya bekerja sebagai android programmer. Karena 'katanya' saya sudah cukup jago di Android (fyi, saya satu-satunya mobile programmer mobile saat itu. Dan satunya lagi programmer web. kami berdua programmer di perusahaan itu). Kemudian selanjutnya saya dichallenge, apakah bisa bikin aplikasi ios juga? Saya menyanggupi challenge tersebut. Sehingga saat ini saya jadi seorang flutter programmer.

Kebingungan yg muncul saat ini adalah, saya merasa keputusan saya saat itu salah. Karena 'jago' yang dibilang ketika itu, tanpa benchmark yg jelas. Alhasil saya yg sedang berprogress ketika itu, kembali lagi menjadi junior dengan mempelajari flutter dari nol.
Kemudian, yg saya lihat kebutuhan di perusahaan besar kebanyakan mencari programmer mobile native (android/ios). Dan itu lebih menjanjikan jenjang karir yang jelas. 

Saya minta masukan dan sarannya, berdasarkan pengalaman kawan-kawan sekalian di sini, langkah apa yang sebaiknya kemudian saya ambil agar karir saya bisa lebih terarah? Sebelum saya semakin terlambat lagi membuat keputusan.

Catatan:
- Dalam tengah perjalanan tersebut covid menyerang. Syukur perusahaan tempat saya bekerja bisa survive. Sementara banyak terjadi PHK di mana-mana. Sehingga pilihan ter-aman adalah saya mesti bertahan di sini. 
- Saat ini saya multitasking single salary di sini. Ya ngedesain UI/UX web dan mobile, ngoding frontend web, ngoding flutter, dan mentoring 1 junior saya.
Saya kira saat ini saya bisa mulai merencanakan karir saya ke depannya. 

Terima kasih sudah membaca issue ini.

**Comment by yuzutaru** [comment]
As a fellow android developer, saya bantu jawab ya, tapi ini opini dari pengalaman saya aja si.

Menurut saya baik mobile, web, atau front end itu perkembangan teknologi nya cepet. ya kita dituntut harus selalu belajar. Saya juga ngalamin kayak mas, tapi saya native android developer. merasa jago. Tapi lamar perushaan yang lebih bagus keok. ya belajar lagi, belajar terus. dulu saya malah Java. Belajar lagi buat kotlinnya.

Untuk jenjang karir saya kira sama. ada alasan masing2 perusahaan develop native or hybird (flutter dalam hal ini).
Perusahaan besar, staff banyak. bisa jadi mereka develop native, karena punya programmer masing2. native experience tetap beda saya rasa dengan hybird.
untuk hybird kelebihannya, code base android/ios bisa sedikit lebih mudah ke maintain. development speed bisa lebih cepet. cost lebih murah. design flutter juga keren2, yang saya rasa ada beberapa  ribet buat di implement di native.

kalo untuk masalah tempat kerja itu udah biasa si multi tasking. Apalagi klo perusahaannya masih dikit staffnya. Saya dulu 2 tahun awal pegang android cordova, java sama .net backend. yang akhirnya nyesal, karena 3 3 nya gk jago amat, knowledge so so. Akhirnya saya fokusin di android native saja. Akhirnya cari pekerjaan baru yang memang spesifik android developer.

**Comment by fityanrahman** [comment]
Sepakat. Saya mesti belajar lebih lagi, dalam upaya restrukturasi karir saya.

Saya juga termasuk programmer yg concern terhadap performa aplikasi. Sepertinya saya akan cenderung memilih kembali ke jalur native. Sebelum semakin terlambat. 
Pertimbangannya, saya kira native masih lebih menjanjikan untuk jangka panjang. Sementara jika saya fokus di hybrid seperti flutter, saya mungkin akan melewatkan best practice dari kedua platform (android/ios) tersebut. Misal, material design yang saat ini sudah masuk v3, atau cupertino di ios, dan hal-hal fundamental lain di keduanya. 

Untuk hybrid, saya kira memang lebih pintas dan efisien untuk perusahaan, apalagi masih dikit staffnya seperti tempat saya sekarang. Tapi bukan best option bagi karyawan, yg masih punya impian karir yg masih panjang. 

Ini yg saya mulai rasakan juga sekarang, penyesalan terlalu tau banyak, tapi ga jago amat. Dan menyesal sudah mengenalkan flutter ke bos saya.

Terima kasih banyak atas jawabannya mas @yuzutaru. Senang bisa dijawab oleh fellow android developer seperti mas.

**Comment by fityanrahman** [comment]
Btw, kenapa perkembangan mobile hybrid seperti flutter dan react native masih tetap naik trendnya ya? Padahal secara experience, bagaimana pun tetap akan berbeda dengan native. Dan perusahaan yang mengembangkan aplikasi besar, tentu akan memprioritaskan performa produknya, ketimbang efisiensi SDM, dalam hal ini jumlah karyawan. Pengembang aplikasi besar, tentu saja perusahaan besar yang tidak akan memikirkan hal kecil seperti itu.

**Comment by yuzutaru** [comment]
untuk flutter sendiri di support langsung google, jadi gk menutup kemungkinan kedepannya buat performance. Flutter juga ada flutter web, jadi memungkinkan develop 3 platform sekaligus, android, ios, web

company pasti cari profit, pakai flutter bisa menghemat sehingga profit nambah. dari pada hire 2 developer android and ios. bisa 1 developer.

kalo opini saya si. Hybird itu ada biar programmer web lebih mudah develop apps mobile. Di beberapa youtube flutter sm react native itu gampang di pelajari sm front end web.adaptasi mereka cepet.

**Comment by fityanrahman** [comment]
Betul, saat ini sudah masuk stable channel malah. 

Mungkin itu berlaku untuk perusahaan kecil sampai menengah mas? 

Menurut mas pribadi, kapan hybrid bisa jadi ancaman native?

**Comment by yuzutaru** [comment]
Belum tentu juga, perusahaan besar juga mulai cari si, pengalman taun lalu intense cari kerja, uda mulai banyak kebutuhan flutter.

Ane sndiri sama sekali belum nyobain flutter, tapi sering nonton orang bahas. Dari info yang saya terima, native itu dibutuhin untuk manggil library2 hardware kayak, camera, gps, accelorometer. Nah kalau di flutter butuh plugin buat jembatanin kesitu, yang mana pluginnya itu native. nantinya kalo performa flutter bagus, native ttp dibutuhin buat akses hardware. CMIIW

kalo yang saya lihat sekarang si masih jalan ke 2 nya, gak tau dalam 2- 5 tahun lagi. 
kalo kita butuh aplikasi yang gk banyak akses hardware, pengen cepet develop, ya flutter. Tapi kalo apps nya butuh akses hardware, mungkin lebih baik native.

**Comment by fityanrahman** [comment]
Nah loh.. Saya belum sempet eksplor sejauh itu juga sih

Yaps mas. Kita tetep ngoding androidmanifest.xml ketika manggil library hardware android, juga info.plist untuk ios. Memang harus mengerti fundamental kedua platform tsb.

Hmm.. Yg bikin menarik karena google yg bikin ya. Beda ketika Microsoft bikin Xamarin yg sekarang nasibnya entah gimana. 

Makasih banyak pandangannya mas. Semoga saya bisa segera memutuskan pilihan saya tanpa gegabah.
