### ISSUE TITLE
Apa itu Problem pada N + 1 Query ?

### ISSUE THREAD

**Issue by bagusgandhi** [ProgrammerZamanNow/qna#330]
Halo pak Eko, 
saya mau bertanya mengenai problem N + 1 Query. Saya masih agak kebingungan mengenai hal ini, minta pencerahannya dong pak eko.

**Comment by farhan15r** [comment]
misalkan kita mempunyai tabel **manusia** dan juga tabel **jenis kelamin**, dan kedua tabel tersebut berelasi/terhubung **one to many**, yang berarti tabel **jenis kelamin** dapat digunakan oleh beberapa record dari tabel **manusia**.

Problem N+1 adalah problem dimana saat kita query pada tabel **manusia** untuk mendapatkan seluruh record-nya ia akan query lagi sebanyak jumlah record manusia ke tabel **jenis kelamin** untuk mendapatkan data jenis kelaminnya.

misalkan ada **10** record pada tabel **manusia**, (ini berarti sudah query sebanyak 1x),
setelah dapat record-nya maka akan ada query lagi ke database untuk mengetahui jenis kelamin dari setiap record,
karena pada tabel manusia hanya memiliki **id jenis kelamin**, untuk mendapat jenis kelaminnya maka setiap record akan query untuk mencari jenis kelamin berdasarkan **id jenis kelamin**, 
Karena tadi ada 10 record pada tabel **manusia** maka akan dilakukan query sebanyak 10x ("N") untuk mendapatkan jenis kelamin dari setiap record.

**Comment by khannedy** [comment]
https://youtu.be/x5tc6gR1HiU
