### ISSUE TITLE
Stream file excel berisi 500k rows

### ISSUE THREAD

**Issue by akhirwan** [ProgrammerZamanNow/qna#344]
Halo Kang Eko,
saya seorang golang developer di suatu corporate FMCG yang sedang digitalisasi semua data yang kami punya.
saya diberi satu task untuk memindahkan data dari file spreadsheet (excel) ke Postgresql,, untuk data di bawah 10k rows service golang masih aman,,nah issue nya ketika ada data yang memiliki 500k rows atau lebih,,ketika test di laptop (core i3 - RAM 8Gb - SSD 256),,laptop saya terkena out of memory,,mungkin kang Eko ada best practice untuk handle issue tersebut dari sisi logic di service nya? (untuk upgrade device / server itu opsi terakhir saya)

terima kasih Kang.

**Comment by khannedy** [comment]
https://youtu.be/POifpGE-Vfg

**Comment by akhirwan** [comment]
di private Kang
