### ISSUE TITLE
Apakah penggunaan clean architecture itu penting?

### ISSUE THREAD

**Issue by elliuqahs** [ProgrammerZamanNow/qna#361]
Saya pernah menanyakan ke teman saya tentang pengalaman dia di tempat kerja. Katanya beberapa perusahaan yang pernah menjadi tempat kerjanya tidak menerapkan clean architecture , hanya MVx biasa (saya tidak tau detail teknis patternnya). Jadi apakah clean architecture ini penting? apakah ada kekurangan dari pattern ini , sehingga beberapa perusahaan tidak menerapkan nya?

**Comment by mariesto** [comment]
Izin bantu jawab @shaqna 

Clean architechture memang bukanlah sebuah approach yg harus di-implement.
Tapi jika kita lihat definisi nya secara sekilas, clean architecture ini adalah salah satu bagian dari software design pattern.
Dan software design pattern ini biasanya diimplementasikan dengan menggunakan SOLID Principles.

Dari background tersebut, bisa dikatakan ini adalah sebuah approach yg digunakan untuk menciptakan sistem yg robust dan memiliki resilience lebih baik dibanding sistem yg tidak mengimplementasikan clean architechture.

Approach dari clean architechture ini menurut saya pribadi memiliki beberapa concern :
- Diperlukan pemahaman yang baik untuk menerapkan clean architecture ini
- Memerlukan waktu yg relatif lebih lama untuk mengimplementasikan clean architecture karena harus di design dengan benar sejak awal sesuai use case
- Tapi dengan concern tersebut, kita mendapatkan keuntungan dari sistem yg lebih robust dan resilience 
- Dan clean architecture bukanlah sesuatu yg selalu terikat dengan sebuah bahasa pemrograman, tapi bersifat agnostik dan applicable terhadap bahasa pemrograman lain

Reference : https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

**Comment by khannedy** [comment]
https://youtu.be/Naq5js9SQOM
