### ISSUE TITLE
Apakah jwt aman ?

### ISSUE THREAD

**Issue by ghalmasshandityaaa** [ProgrammerZamanNow/qna#368]
JWT sangat populer untuk autentikasi token karena di tanda tangani, saya pernah mencoba menggunakannya, sign token jwt menggunakan method RS512 dengan menggunakan private dan public key, alhasil latency untuk create access atau refresh token lebih tinggi daripada menggunakan HS256. Ketika hasil dari sign saya coba pada laman jwt.io benar sekali token tersebut tidak bisa di decode tanpa key. Tetapi apabila menggunakan method HS256 token tersebut akan muncul data header dan payload ketika di decode di lamat jwt.io. Saya pikir RS512 aman, tetapi ketika saya decode menggunakan library (jwt-decode) token dengan method RS512 dapat didecode tanpa menggunakan key. Jadi apakah Jwt itu aman ? lebih baik menggunakan jwt atau membuat token yg kita enkripsi dengan string key atau public dan private key ?

**Comment by khannedy** [comment]
https://www.youtube.com/watch?v=6hukSEBS6Vw&ab_channel=ProgrammerZamanNow
