### ISSUE TITLE
Mengapa butuh proxy ketika connect ke database?

### ISSUE THREAD

**Issue by ariefsibuea** [ProgrammerZamanNow/qna#369]
Halo Mas Eko, izin bertanya. Dalam pengembangan aplikasi yang nantinya akan di-deploy ke staging/production, tidak terhubung/connect secara langsung ke database, tetapi melalui semacam connector atau proxy, misalnya cloud-sql-proxy atau penggunaan ProxySQL & Percona. Boleh request dijelasin gak Mas mengapa kita butuh proxy tersebut? Karena kalau demo-in di local aplikasi terhubung langsung ke database (local), namun berbeda cerita kalau sudah di staging/production. Kemudian, boleh dijelasin juga gak Mas kira-kira flow pemrosesan request dari aplikasi sampai ke database ketika system menggunakan connector/proxy? Misalnya di kasus cloud-sql-proxy atau penggunaan ProxySQL & Percona.

Terima kasih Mas.

**Comment by khannedy** [comment]
https://youtu.be/jPMk1poRhzU

**Comment by ariefsibuea** [comment]
Thank you mas @khannedy
