### ISSUE TITLE
Mengirim jutaan notification

### ISSUE THREAD

**Issue by triadmoko** [ProgrammerZamanNow/qna#370]
Saya memliki studi kasus dimana setiap hari aplikasi akan mengirimkan notifikasi ke seluruh user agar aplikasi dapat berinteraksi dengan user.

Bagaimanakah caranya agar notification dapat terkirim ke seluruh user dan perfomance server tidak terganggu. 

Terimakasi mas eko.

**Comment by khannedy** [comment]
https://youtu.be/VzaLAAYxqkc

**Comment by triadmoko** [comment]
Mantap mas. Terimakasih mas eko
