### ISSUE TITLE
Lalu gimana best practice untuk pindah tipe database dari sql ke nosql maupun sebaliknya 

### ISSUE THREAD

**Issue by udinesia325** [ProgrammerZamanNow/qna#392]
Setelah menonton video pembahasan kak Eko sebelumnya saya memutuskan untuk berpindah dari sql ke nosql, nah apakah ada best practice nya ?. begitu pun sebaliknya yaitu dari nosql ke sql
Terimakasih

**Comment by jittermitter** [comment]
Hi @udinesia325 saya coba jawab yah
Hmm mungkin sebaiknya gak usah pindah sih, tapi mungkin di duplikasi saja datanya, mislnya contoh yg tadinya dari SQL, bukan menghilangkan SQL tapi lebih ke duplikasi saja datanya dari SQL ke NoSQL, mislnya contoh data2 yg banyak joinnya di SQL, itu coba di denormalisasi trus copy ke database NoSQL, nanti ketika mau query, langsung saja ke NoSQL

Semoga menjawab yah

**Comment by udinesia325** [comment]
Oke makasih
