### ISSUE TITLE
Kerja sama tim yang baik itu seperti apa terutama dalam bidang programming

### ISSUE THREAD

**Issue by AdiCahyaSaputra** [ProgrammerZamanNow/qna#4]

**Comment by bailram** [comment]
bantu jawab bang adi

kalau di programming untuk melakukan kerja sama antar developer ini diperlukan kemampuan git, karena setau saya hampir diseluruh perusahaan sekarang untuk bekerja sama semuanya menggunakan git.

kemampuan untuk membaca dokumen kebutuhan / spesifikasi.

di bidang programming ini biasanya setiap tim bukan hanya programmer aja isinya, tapi ada business analyst, ui/ux, QA, dll. asalkan kita bisa mengkomunikasikan apa yang perlu ada perhatian atau hal yang mau ditanyakan, harusnya aman aja bang. yang penting komunikasi, jangan mentang-mentang jadi programmer gak mau bersosialisasi. justru programmer ini kalau gak bisa komunikasi pengembangan fitur gak akan sesuai dengan yang diinginkan

semoga membantu

**Comment by AdiCahyaSaputra** [comment]
Thanks bang jawabannya
