### ISSUE TITLE
Bagaimana penerapan CI/CD pada shared hosting?

### ISSUE THREAD

**Issue by Sch39** [ProgrammerZamanNow/qna#468]
Saya baru belajar terkait DevOps, dari yang saya pelajari saya menyimpulkan dimana untuk menerapkan CI/CD diperlukan tools yang dalam pengoperasian dan penginstalan biasanya harus memiliki akses ke terminal ataupun dari pengaturan server yang lebih dibandingkan pada shared hosting yang terbatas, jadi apakah bisa menerapkan CI/CD pada shared hosting?, jika bisa apakah itu worth it dan bagaimana caranya?

// pertanyaan ini saya ajukan karena biaya sewa shared hosting lebih murah, hehe🤣

**Comment by nggepe** [comment]
Bisa dong saya juga biasanya tetep pakai cicd meskipun menggunakan shared hosting. Yang penting hostingnya ada ssh-nya. Untuk remote ssh saya biasanya pake cicd punyanya appleboy.

**Comment by Sch39** [comment]
Ok makasih mas jawabannya.
