### ISSUE TITLE
Ada yang pernah bilang kalau buat pemula lebih baik pilih frontend dulu. Perusahaan gamau hire backend pemula karena takut ngerusak sistem. Apakah itu benar?

### ISSUE THREAD

**Issue by PrinceSondakh** [ProgrammerZamanNow/qna#47]

**Comment by pokopang07** [comment]
tidak benar. karena ketika develop sesuatu pasti akan direview terlebih dahulu oleh leader/atasan nya. jadi harusnya sistem gk mungkin dirusak oleh dev pemula. 
pas seleksi kandidat juga harusnya di test dlu si dev pemula ini mumpuni atau enggak untuk gabung perusahaan.

mudah2an bisa menjawab.

**Comment by PrinceSondakh** [comment]
Maaf bro, saya masih kurang puas bro 🙏

**Comment by pokopang07** [comment]
sure sure no worries

**Comment by rsetiawan7** [comment]
Kalau dibilang takut merusak sistem, sepertinya agak aneh sih.

Mungkin yang tepatnya itu review hasil kerjaan junior-nya belum begitu ketat di perusahaannya, seperti penerapan pull request yang tidak di-review 1 per 1 file-nya, tidak ada aturan untuk mewajibkan pembuatan unit test, dll.

Kalau dianggap merusak sistem, kan seharusnya sudah dijaga hasil kerjaannya sebelum diserahkan.
Kalau kerjaan sudah diserahkan dan bikin merusak sistem, berarti kemungkinan besarnya hasil kerjaannya tidak diperiksa dengan baik.

**Comment by PrinceSondakh** [comment]
@rsetiawan7 i see , thankyou bro, gw kira ngacak ngacak sistem bisa terjadi, tapi trnyt lebih masuk akal jika pada proses pemeriksaannya kurang teliti. Case closed.
