### ISSUE TITLE
Bahas cara optimasi di bagian Frontend dong kang Eko

### ISSUE THREAD

**Issue by fahmiidris** [ProgrammerZamanNow/qna#476]
Assalamualaikum kang eko, setiap saya dengar tentang optimasi pasti langsung merujuk kebagian Backend, entah itu auto-scaling, micro-service, atau lain nya. Nah, kalo di bagian frontend ada gak sih? Terima kasih

**Comment by localhousee** [comment]
setau saya dari sisi browser sih paling umum nerapin lazy load biar user hanya load image waktu gambar dah di dalem viewport

contoh lain, hasil bundling JS dipecah2 jadi beberapa file, efeknya waktu pindah page, hanya load script js yang diperluin aja
