### ISSUE TITLE
Version Control System untuk Database SQL

### ISSUE THREAD

**Issue by vierilusen** [ProgrammerZamanNow/qna#477]
Kalo di source code kan kita menggunakan git ya untuk version control system nya, nah saya mau nanya best practicenya kalo untuk database khususnya yang sql itu gmna ya menerapkan version control system nya? apakah kita simpan juga file sqlnya di git atau kah dengan menggunakan sistem migration seperti di laravel atau ada cara yang lebih baik? terutama untuk sistem yang shared database, cukup sulit memanagenya seperti conflict dll.

**Comment by khannedy** [comment]
https://youtu.be/YAsWwyXcnWQ
