### ISSUE TITLE
Setelah berapa lama kita bisa launching Aplikasi yang kita develop ke Production

### ISSUE THREAD

**Issue by fakhrulnugroho** [ProgrammerZamanNow/qna#509]
Halo Mas Eko, berapa lama sih proses development sebuah aplikasi sehingga kita bisa melakukan publish atau launching ke Production, dan sudah bisa di pakai sama user. Bukan yang asal launching ke Production tapi fitur fitur nya masih under development & masih perlu improvement.

**Comment by agus24** [comment]
kalo gw biasanya bkin app pake versioning

alpha < 0.5.x
beta < 0.9.x
early release < 1.1.0

untuk alpha core feature sudah 80%
untuk beta core feature sudah 100% tapi masih dalam tahap final testing dari QA
untuk early release ini biasanya udah production tapi masih dalam pengawasan biasanya 1 minggu - 1 bulan.
jika udah 1.1.x maka udah fully working semuanya

**Comment by khannedy** [comment]
https://www.instagram.com/p/CqHuBPfv8rr/
