### ISSUE TITLE
Aplikasi web lambat di hosting atau server cloud, tetapi RAM dan Storage tidak menunjukan masalah

### ISSUE THREAD

**Issue by arkisme99** [ProgrammerZamanNow/qna#53]
Misal dalam 1 server isinya berupa website, dan aplikasi2 lain,. Dengan domain masing2 untuk mengakses nya

Suka ada kendala sewaktu2 untuk akses semua yg berhubungan ada didalam server tersebut itu lambat sekali. 
Jadi perlu di restarrt dahulu servernya, agar normal kembali. 

Dicek di gtafik penggunaan RAM storage dan lainnya, tidak menunjukkan kondisi tinggi (normal) 

Itu kira2 penyebabnya apa ya?

**Comment by iqlal** [comment]
Bisa lebih spesifik mas, appnya apa aja...
Atau bisa diskusi sama saya, monggo...

**Comment by arkisme99** [comment]
Server cloud menggunakan ubuntu 18.0
RAM 3GB
Storage SSD... 

Sudah install apache, mysql. 
Untuk menjalankan beberapa project buatan sendiri, seperti project aplikasi kasir toko dsb. , termasuk beberapa website (folder project website) 

Contoh lambat terjadi ketika ada banyaknya transaksi di aplikasi kasir toko., sehingga menyebabkan semua project yg ada di dalam server juga lambat untuk diakses. 

Sehingga saya perlu restart server dahulu, lalu normal kembali. 

Seperti itu mas @iqlal , kira2 paham yg saya maksud?

**Comment by iqlal** [comment]
@arkisme99, ok mas paham,
✅ itu PHP sudah di-tweak resources-nya (dibatasi aja sesuai kemampuan server) ?
✅ coba test di lokal misal pakai openlitespeed apakah lebih baik ? karena beberapa benchmark menunjukkan OLS lebih baik dari pada Apache
✅ tertulis "Sehingga saya perlu restart server dahulu, lalu normal kembali.", coba lihat task yang berjalan dan coba cek satu persatu apakah ada yang tidak diperlukan atau tidak

**Comment by arkisme99** [comment]
Sorry baru di respon

Ditest di lokal aman, 

Saya pernah coba cek di grafik server itu sering terjadi hanya di jam tertentu.

Kemungkinan terjadi, memang ada transaksi yg banyak di jam tersebut, atau user dari aplikasi sedang melakukan penarikan laporan dengan range waktu panjang (1 tahun) misal. 

Jadi sepertinya itu karena bandwidth nya terlalu banyak kali ya, sehingga beban ke server. 

Jadi apakah ada cara untuk mengatasi bandwidth yg berlebih itu ya?

**Comment by haydaraji** [comment]
semingguan coba pake DewaCloud, recomended sih, base nya pakai Jelastic, support Load Balancer, bisa autoscaling, billing dikenakan sesuai trafic CPU/RAM yang digunakan
![Screen Shot 2022-06-03 at 11 23 25 AM](https://user-images.githubusercontent.com/54424902/171785877-d207e800-4288-4390-9c05-5ce19c8ef9e5.png)
n

**Comment by khannedy** [comment]
https://youtu.be/y6U9ZVBt83U

**Comment by arkisme99** [comment]
> https://youtu.be/y6U9ZVBt83U

Terimakasih pak Eko 😁

**Comment by zerofinding** [comment]
https://httpd.apache.org/docs/2.4/mod/event.html

*bisa non-blocking juga ya' Apache
