### ISSUE TITLE
Perbedaan Fork dan Cluster di Nodejs dan fungsinya 

### ISSUE THREAD

**Issue by jdnielss** [ProgrammerZamanNow/qna#532]
Selamat malam pak eko, saya kebingungan dengan mode Fork dan Cluster di Nodejs. soalnya masih jarang yang bahas dalam bahasa indonesia dan study casenya seperti apa jika ingin memakai mode fork atau cluster

**Comment by khannedy** [comment]
https://youtu.be/8eGLDBQ2Kdc

**Comment by jdnielss** [comment]
makasih banyak pak eko atas penjelasaannya
