### ISSUE TITLE
Apa bahasa pemograman yang paling sering digunakan di perusahaan besar sekelas Tokopedia, Shoppy, BliBli

### ISSUE THREAD

**Issue by lambebawah** [ProgrammerZamanNow/qna#562]
jadi saya seorang freelance php, pengalaman susah banget maintenance web ketika mysql sebesar 50gb ke atas dengan platform wordpress, sempat saya sarananin client saya pakai service wordpress VIP, tapi ya gitu harganya mehong banget.

facebook juga ngalamin hal yang sama pas awal awal , terus di koding lagi php itu pakai C++

**Comment by khannedy** [comment]
tokopedia pake golang
shopee gak tau pake apa
blibli pake java
tiket pake java
gojek pake java, clojure, golang
traveloka pake java
