### ISSUE TITLE
Belajar Database ACID (Atomicity, Consistency, Isolation, Durability)

### ISSUE THREAD

**Issue by 1tsme33** [ProgrammerZamanNow/qna#565]
Pada materi database ACID dijelaskan bahwa perlu sebuah aturan pada level database agar tetap mengikuti ketentuan dan kepatuhan. Pertanyaanya adalah apakah kita perlu melakukan validasi lagi pada level aplikasi, sedangkan kita sudah membuat aturan pada level database.

Best practicenya bagaimana?

**Comment by rusmanplatd** [comment]
kalau saya buat validasi berlapis dari db -> be -> fe

**Comment by khannedy** [comment]
idealnya di semua bagian ada aturan, kalo gak, nanti semua selalu bergantung ke database. dan kita juga nanti kenyataannya gak semua database menggunakan relation yang ACID, pada NoSQL, banyak juga yang gak ACID
