### ISSUE TITLE
Idempotent Request

### ISSUE THREAD

**Issue by andresnodas** [ProgrammerZamanNow/qna#566]
Ada best practice agar API kita menjadi idempotent terutama API yang berupa transaksi insert ke database?
Agar bila terjadi double call ke API kita tidak terjadi double insert. 

Terima Kasih

**Comment by fransfilastap** [comment]
Client harus generate Idempotence Key.

**Comment by khannedy** [comment]
https://www.youtube.com/watch?v=qnxwOX2s1RA&ab_channel=ProgrammerZamanNow
