### ISSUE TITLE
Nanya Serius Inimah

### ISSUE THREAD

**Issue by refaldyrk** [ProgrammerZamanNow/qna#57]
Apakah seorang back end di industri harus bisa docker?

Nanya beneran, yang lain kalo mau jawab silahkan 🙏

**Comment by hafiyyanabdulaziz** [comment]
Di kantor aku engga, ada orang lain yg ngurusin bagian itu

**Comment by zycoder142** [comment]
Untuk docker biasanya ada bagian khusus nya yaitu bagian devops.. kalo seorang backend paham itu sebagai nilai plus.

**Comment by refaldyrk** [comment]
Thank Youu Yang Udah Jawabbb @zycoder142 @hafiyyanabdulaziz
