### ISSUE TITLE
JDK versi berapa yang cocok dipakai jika kita baru mau memulai mengembangkan aplikasi java di saat sekarang ini?

### ISSUE THREAD

**Issue by fauzyd2** [ProgrammerZamanNow/qna#579]
Halo, Mas Eko. Saya baru mempelajari dan ingin mencoba membuat aplikasi dengan Java, tapi masih bingung untuk menggunakan JDK versi berapa. Maaf pertanyaannya newbie sekali :)

**Comment by khannedy** [comment]
JDK 17, yang LTS terbaru
