### ISSUE TITLE
Kapan Saat yang tepat untuk Resign dari perusahaan Sekarang?

### ISSUE THREAD

**Issue by KAnggara75** [ProgrammerZamanNow/qna#582]
Maksudnya saat kondisi seperti apa, yg mengharuskan sepertinya resign adalah pilihan yg terbaik...

**Comment by aditiyadwiramadani88** [comment]
https://youtu.be/wwkE1M7k89Y

**Comment by KAnggara75** [comment]
Closed, thanks
