### ISSUE TITLE
Dengan munculnya Github Copilot atau semacamnya dan mungkin saja semakin canggih kedepannya serta mungkin industri lebih memilih hal ini, apakah job programmer akan terancam berkurang? atau bahkan tergantikan?

### ISSUE THREAD

**Issue by mdafaardiansyah** [ProgrammerZamanNow/qna#6]

**Comment by herlanmustopa** [comment]
bantu jawab, 
Copilot itu tidak akan mengganti peran programmer, namanya aja copilot bukan pilotnya, hanya sebagai pendamping saja.
dan sepengalaman saya copilot itu hanya akan cocok digunakan untuk programmer yang udah berpengalaman, orang yang baru belajar prgramming pasti akan tetap bingung dengan fitur yang disediakan oleh copilotnya itu sendiri.
jadi tetap peran pilotnya ( programmer) itu akan selalu menjadi main nya nya..
jadi kesimpulanya itu ngga akan.

**Comment by Akbar0102** [comment]
yang bikin copilotnya kan programmer. mungkin kasus kaya bikin web bisa pake template2 yang langsung jadi tapi tetep frontend masih banyak lowongannya
