### ISSUE TITLE
Udemy dan Youtube Free

### ISSUE THREAD

**Issue by staticox24** [ProgrammerZamanNow/qna#611]
Pak Eko, mau nanya perbedaan saya berlangganan course javascript dengan video youtube free playlist javascript. Kalo saya liat dari segi materi sepertinya sama aja dan juga kira kira promonya kapan yah pak. Promo terakhir saya ketinggalan.  Huaaaa. Terima kasih sebelumnya pak

**Comment by learncodealways** [comment]
Ada materi lanjutan

**Comment by staticox24** [comment]
Apa aja yah? Yang saya liat  sama saja

**Comment by dinarwijaksono** [comment]
youtube free ada vidoe yg tidak bisa di lihat oleh member biasa, ada beberapa video yg hanya bisa di lihat dengan berlangganan memeber pzn, 

berlangganan di youdemi hanya pilih salah satu playlist saja tetapi sekali bayar untuk seumur hidup dan ada beberapa video yang hanya di upload di youdemi (tidak di upload di youtube juga)

waktu promo waktunya random, tetapi paling sering sih pak eko adain promo pas akhir bulan mendekati awal bulan (promo gajihan)

**Comment by khannedy** [comment]
tidak semua materi di gratiskan di youtube
