### ISSUE TITLE
krisis identitas

### ISSUE THREAD

**Issue by frostdev03** [ProgrammerZamanNow/qna#619]
Di sekolah diajarin mobile pake java, tp yg kepake byk di kuliah malah kotlin atau dart. Lebih baik stay java atau menyesuaikan yg byk kepake di kondisi sekarang bang?

**Comment by raselldev** [comment]
tergantung tujuannya, kalo mau fokus di android bisa pakai java/kotlin, 

jika mau multiplatform bisa kotlin/dart
