### ISSUE TITLE
SpringBoot untuk cita cita backend Dev

### ISSUE THREAD

**Issue by IrvanWijayaSardam** [ProgrammerZamanNow/qna#62]
Saat ini saya masih semester 4 dan ketika lulus nanti ingin menjadi backend dev dikarenakan dari SMK (RPL) saya sudah belajar  programming dan saya kira saya lebih cocok di backend, saat ini saya sedang memperdalam Spring Boot untuk digunakan sebagai senjata utama ketika lulus nanti , apakah hal yang saya lakukan sudah benar / ada saran dari pak Eko agar saya tidak salah langkah dri awal, terimakasih.

**Comment by khannedy** [comment]
banyak di dunia kerja yang pake spring boot
