### ISSUE TITLE
are stored procedure is relevant?

### ISSUE THREAD

**Issue by alfaben12** [ProgrammerZamanNow/qna#625]
fun fact: ditempatku lebih tepatnya timku sama sekali enggak pakai

pertanyaan tambahan, apakah blibli pakai stored stored procedure pak?

Thanks :love_letter:

**Comment by brainplusplus** [comment]
Bantu jawab, harusnya di Blibli versi sekarang gak pakai (tapi mungkin di pakai di Blibli versi awal jaman monolith)

Alasannya, karena stored procedured susah di versioning, sudah di debugging, susah di scaling

jadi saya jamin 1 juta persen Blibli tidak ada stored procedure
