### ISSUE TITLE
Git Flow yang bagus seperti apa

### ISSUE THREAD

**Issue by alditegarprakoso** [ProgrammerZamanNow/qna#626]
Pak Eko saya mau tanya, untuk Git Flow yang bagus untuk sebuah project itu seperti apa ? Misalkan kita ada 3 environment (Dev, Staging, dan Production). Jika kita ingin menambahkan sebuah fitur, fixing bug (bugfix, hotfix), atau ada enhancement itu baiknya seperti apa ya pak ? Dan itu kita ambilnya dari environment mana ya pak jika ada case-case tersebut. Terima kasih Pak Eko

**Comment by khannedy** [comment]
https://youtu.be/bB1WAeEbz7I
