### ISSUE TITLE
Apa saja yang perlu disiapkan ketika ingin pindah tempat kerja? 

### ISSUE THREAD

**Issue by rizkikosasih** [ProgrammerZamanNow/qna#631]
Saya sudah 2.5 tahun lebih bekerja sebagai programmer tapi tidak bisa berkembang, dan akhirnya ketika ingin pindah tempat kerja membuat saya tertinggal dari segi pengalaman dalam bidang ini.

Jujur saja pengalaman saya sedikit, jadi saya ingin bertanya apa saja sih yang perlu disiapkan atau apa yang paling umum dibutuhkan perusahaan ? Agar saya dapat mempelajarinya terlebih dahulu

**Comment by brainplusplus** [comment]
sering-sering lihat lowongan pekerjaan di jobstreet, linkedin, kalibbr sesuai bidang yang diminati

semisal search aja di situs2 tersebut "backend developer"

nah, nanti nongol deh lowongannya, trus lihat spesifikasinya

misalkan, 

- terbiasa unit test
- mengerti docker dan kubernetes
- punya pengalaman minimal 2 tahun di NoSQL (mongodb)
- punya pengalaman minimal 2 tahun dengan RDBMS
- punya pengalaman dengan messaging (RabbitMQ, Kafka)
- punya pengalaman dengan cloud (GCP, AWS)

atau ini deh contoh lowongan traveloka di linkedin

Required skills:

Experience with Java, both plain Java and Spring Boot framework
Experience with SQL-based RDBMS, preferably PostgreSQL
Experience with writing Unit Test with any Unit Test Framework
Fluency with English, both oral and written

Nice-to-have skills:

Experience with any cloud infrastructure such as AWS or GCP is preferred
Experience with Infrastructure-as-a-Code system such as Terraform is preferred
Experience with NoSQL DBMS such as MongoDB or Redis is preferred
Experience with either Python or JavaScript is preferred
Experience with Microservice architecture is preferred
Experience with CI/CD systems is preferred

Nah, dari situ kita akan evaluasi, kira-kira apa yang kurang di kita yang bisa kita pelajari sebelum melamar pekerjaan

kebetulan saya sering lowongan pekerjaan, jadi rata-rata spesifikasinya mirip2 sih

**Comment by rizkikosasih** [comment]
Terima kasih atas sarannya mas
