### ISSUE TITLE
Bagaimana cara komunikasi ke database yang efektif ?

### ISSUE THREAD

**Issue by Torao-Law** [ProgrammerZamanNow/qna#637]
Saya ada case kalau ingin menyimpan data ke dalam database :
- Casenya : ID menggunakan random generate dari UUID, karena casenya ID adalah primary key berarti harus unik.

Mungkin flow yang selama ini yang terimplementasi adalah :
1. User Controllers 
- Setelah generate UUID saya melakukan COUNT / FIND ke database jika ada maka saya melakukan generate UUID kembali hingga null / belum pernah terpakai
- Jika proses sebelumnya sudah selesai baru saya melakukan INSERT ke database.

2. User Service (saya deklarasikan fungsi terpisah dalam satu file)
- Method Find / Count.
- Method  INSERT

Jika yang saya amati berarti ketika saya melakukan create new user. berarti saya melakukan 2x komunikasi kedatabase yaitu pertama FIND / COUNT dan kedua INSERT. apakah cara seperti ini sudah benar dalam case ini atau ada cara lain.. Mohon pencerahannya.. Terima kasih yang sebanyak-banyaknya

**Comment by abitama-satria-LO** [comment]
Menurut saya caranya tidak tepat, karena seperti yg udah ditulis sendiri: ada langkah buat nyari dulu sebelum di-insert ke tabel.

Menurut saya lagi, langkah buat nyari ID-nya bisa dihilangkan karena peluang collision UUID kecil banget, bahkan terlalu kecil untuk dijadikan concern (boleh baca [artikel ini](https://jhall.io/archive/2021/05/19/what-are-the-odds/)).

**Comment by khannedy** [comment]
https://youtu.be/QEEWbyNUeB0
