### ISSUE TITLE
API BPJS KETENAGAKERJAAN?

### ISSUE THREAD

**Issue by igoynawamreh** [ProgrammerZamanNow/qna#639]
Apakah BPJS KETENAGAKERJAAN memiliki API untuk sekedar cek data peserta, seperti: nama, program yang diikuti, tanggal efektif, tanggal berakhir?

**Comment by narwinoks** [comment]
setahu saya ada namun untuk integrasi nya harus secara resmi pengajuan kepihak BPJS.

**Comment by khannedy** [comment]
saya tidak kerja di BPJS
