### ISSUE TITLE
Perbedaan senior programmer vs junior programmer dalam hal teknis

### ISSUE THREAD

**Issue by ihsansfd** [ProgrammerZamanNow/qna#64]

**Comment by mad-af** [comment]
code style pastinya wkwk

**Comment by nurrohim11** [comment]
bantu jawab bang, perbedaan yang paling signifikan mungkin di gaji dan benefit nya sih dan tentunya tanggung jawba. wkwkw

**Comment by localhousee** [comment]
cara solve problemnya kali ya? misal yang junior make foreach dalem foreach, kalo senior mungkin ntah make binary search atau algorithm lain yang secara performance lebih cepet

**Comment by mad-af** [comment]
> 

Waduh engga dung, iya efesien di performance, engga di ngoding nya wkwk. itu pun masih belum pasti lebih efesien, dibanding method bawaan bahasanya. soalnya setahuku better manfaatin sebaik mungkin method2 bawaan bahasa nya

**Comment by localhousee** [comment]
> > cara solve problemnya kali ya? misal yang junior make foreach dalem foreach, kalo senior mungkin ntah make binary search atau algorithm lain yang secara performance lebih cepet
> 
> Waduh engga dung, iya efesien di performance, engga di ngoding nya wkwk. itu pun masih belum pasti lebih efesien, dibanding method bawaan bahasanya. soalnya setahuku better manfaatin sebaik mungkin method2 bawaan bahasa nya

waduh maap bang saya masi junior, wkwk. tengs udah dijelasin

**Comment by khannedy** [comment]
https://youtu.be/PRK7RBFJ-p8
