### ISSUE TITLE
Teknologi database yang tepat untuk data yang update terus menerus setiap 1 menit

### ISSUE THREAD

**Issue by ilfahidayat** [ProgrammerZamanNow/qna#645]
Halo mas eko, DI project kami ada kebutuhan untuk sinkronisasi data dari third party yang di lakukan setiap 1 menit sekali. Kami coba implementasi menggunakan mysql, namun muncul kendala menyebabkan operasi insert di table lain menjadi lambat saat proses sinkronisasi berlangsung. Data yang di update sekitar 1200 record.

Jadi teknik apa yang bisa di lakukan, atau teknologi yang bisa di manfaatkan untuk mengatasi masalah tersebut.

Terima kasih.

**Comment by brainplusplus** [comment]
ini update datanya satu per satu atau bulk update? jika belum bulk update, bisa menggunakan bulk update

**Comment by khannedy** [comment]
https://youtu.be/cTRjXOm502k
