### ISSUE TITLE
Tanya Tentang Framework Yang Sudah Usang

### ISSUE THREAD

**Issue by kura1420** [ProgrammerZamanNow/qna#651]
Assalamu'alaikum Pak Eko,

Saya ingin bertanya terkait framework yang sudah usang atau versi yang sudah lama sekali tidak di upgrade.
Bagaimana menaintenance aplikasi yang sudah live production dengan framework yang sudah ketinggalan version dengan yang terbaru. Karena hal ini menjadi issue di kemudian hari, mulai dari bahasa, os yang sudah tidak support dan hal lainnya.

Tolong sarannya karena hal ini menjadi ke khawatiran saya ketika aplikasi sudah berjalan lama, apakah perlu di rebuild ulang atau tidak. Jika di rebuild maka membutuhkan waktu yang lama dan takut ada flow/bisnis proses yang terlewat atau malah jadi bugs.

Terimakasih.

**Comment by khannedy** [comment]
https://youtu.be/GeqLF8WLswY
