### ISSUE TITLE
Kapan waktu yang tepat menyimpan Image di DB, di Projek atau di Object Storage

### ISSUE THREAD

**Issue by ini-agung** [ProgrammerZamanNow/qna#655]
Bagaimana decision penyimpanan gambar yang tepat, 
1. kapan harus di simpan di project (repository image sama dengan code)
2. disimpan ke DB (base64 etc)
3. disimpan ke Object Storage (Minio etc)

thx.. mohon arahan suhu

**Comment by khannedy** [comment]
https://youtu.be/gcIhL1x7MvQ
