### ISSUE TITLE
Code Convetion

### ISSUE THREAD

**Issue by RamaNova99** [ProgrammerZamanNow/qna#659]
Saya seorang pemula yang sedang belajar mengenai dunia programming, suatu ketika saya membaca artikel mengenai code convention, akan tetapi saya masih kurang paham mengenai code convention?, sebenarnya apa sih itu code convention? Kenapa code convention itu ada? Apakah programmer wajib mengerti dan menguasai code convention itu sendiri? apakah ada sebab akibat yang ditimbulkan code convention ketika produksi?.

**Comment by khannedy** [comment]
https://youtu.be/1qaISt3CWRU
