### ISSUE TITLE
Kapan saat nya kita menggunakan Stored Procedure?

### ISSUE THREAD

**Issue by IlhamX7** [ProgrammerZamanNow/qna#660]
Hallo mas Eko, izin bertanya nih. Di tempat kerja saya sekarang ada banyak sekali menggunakan Stored Procedure di service backend nya padahal proses nya hanya crud bisa dengan sedikit validasi. Yang ingin saya tanyakan adalah kapan saat yang tepat untuk kita menggunakan Store Procedure dan dari segi performance menurut mas Eko bagaimana? 
Terima kasih.

**Comment by khannedy** [comment]
jawaban sederhana, gak perlu pake store procedure lagi

maintainya lebih ribet dalam jangka waktu panjang

lebih baik kodenya dilakukan di aplikasi saja
