### ISSUE TITLE
apakah bisa bagi lulusan soshum/sosial berkarir sebagai developer (fullstack,mobile,dll)?

### ISSUE THREAD

**Issue by fikfikri** [ProgrammerZamanNow/qna#69]
halo bang
saya ingin tanya menurut abang sendiri apakah bisa lulusan ilmu sosial/soshum berkarir sebagai developer (fullstack,mobile,dll)?
karena saya ingin belajar coding serta ingin berkarir di bidang IT

**Comment by muhamadramdani275** [comment]
ijin menjawab bang
sangat bisa, temen saya ada yg dari akuntansi pindah haluan jadi programmer
dan beberapa konten kreator di yutub juga ada yg dari soshum malah pada jadi programmer atau bidang yg berbasis IT
