### ISSUE TITLE
Apa yang membedakan programmer Junior dan Senior dari segi coding skill ? 

### ISSUE THREAD

**Issue by suryakumara** [ProgrammerZamanNow/qna#7]

**Comment by didarizaldy** [comment]
Pembuatan nama variabel, nama class, nama func, logic programnya, perkondisian yg efisien kaya gimana (use case / if else), buat class yg byk isinya biasanya dipisahin gak dijadiin 1

Biasanya plg mencolok disitu lainnya sih sama aja

**Comment by cwicaksono** [comment]
Klo menurut saya karena levelnya senior pasti kan jam terbang udah lama jadi biasanya yang akan membedakan dari sisi coding skillnya
1. Cepat membaca dan memahami alur code yang dibuat oleh tim
2. Ketika membuat kode selalu memikirkan jangka panjang kedepan agar maintenance menjadi lebih mudah
3. Mulai memikirkan optimalisasi di sisi kodingannya, walaupun belum diimplementasikan biasanya akan ada komentar di codenya yang bisa mempengaruhi aplikasi jadi lambat karena kondisi tertentu

**Comment by khannedy** [comment]
https://www.youtube.com/watch?v=PRK7RBFJ-p8&feature=youtu.be&ab_channel=ProgrammerZamanNow
