### ISSUE TITLE
Berdasarkan pengalaman Mas Eko, mana yang lebih baik, expert dalam 1 bahasa pemrograman saja atau bisa dalam 3 bahasa pemrograman berbeda namun tidak expert ke 3 nya.?

### ISSUE THREAD

**Issue by suryakumara** [ProgrammerZamanNow/qna#8]

**Comment by herlanmustopa** [comment]
"menggunakan satu buah pisau dengan ahli akan jauh mematikan dibanding punya 3 pisau dengan skill yang tidak maksimal"

**Comment by mdafaardiansyah** [comment]
Bantu menjawab, 

Pernah diomongin sama Pak Dhika sama Kang Eko di Video ini :
https://youtu.be/2PkWBWhHiwE?t=1410

dijawab sendiri langsung sama Kang Ekonya.

**Comment by CoderJava** [comment]
Kalau saya pribadi jawabannya akan seperti ini.
1. Pertama-tama kuasai dulu salah satu bahasa pemrograman sampai ke expert.
2. Kemudian, belajar bahasa pemrograman lain.

Ini lebih baik menurut saya karena ketika belajar bahasa lain dengan modal expert di 1 bahasa pemrograman akan membantu kita lebih cepat belajarnya ke bahasa pemrograman lain.

**Comment by verryp** [comment]
Menurut saya pribadi, tergantung kebutuhan tempat kita berada. 

Misal kita diperusahaan A butuhnya PHP/Vue berarti kita minimal harus deep kesitu, misal kita diperusahaan B butuhnya Go/React juga sama. Tpi tidak menutup kemungkinan kedua perusahaan tersebut beberapa bulan/tahun kedepan akan "pindah kiblat", misalnya menggunakan Rust/Svelte karna mungkin dgn alasan bahasa yg lain sudah tidak relevan. 

Pertanyaannya apakah kita tetap mau mempertahankan hanya disatu bahasa aja? Tpi ini beda cerita jika memang kita bekerja sendiri ya.

Pointnya adalah, yang perlu kita kuasai itu fundamentalnya mulai dri programming, struktur data, design pattern, dkk. terserah bahasa awalnya apa. Jadi saat kita "terpaksa" pindah bahasa pun, kita bisa cepat adaptnya.

mungkin sedikit tips, biasanya tiap bahasa itu punya idiom sama keunggulan masing2, mungkin ini yg perlu kita pahami dahulu kenapa harus memilih bahasa tersebut sebelum deep/pindah kesitu.

**Comment by khannedy** [comment]
udah terjawab ya
