### ISSUE TITLE
Kondisi/waktu yang tepat untuk resign ?

### ISSUE THREAD

**Issue by IwonGunawan** [ProgrammerZamanNow/qna#9]
izin bertanya mas eko, 
1. Kapan waktu atau kondisi yang tepat untuk pindah tempat kerja, dengan tujuan supaya tetap bisa relevan dan bertahan dengan perkembangan teknologi. 

2. dimasa yang akan datang di antara backend, front end dan android developer, menurut mas eko atau teman" bidang mana yang lebih banyak di cari dan terus berkembang.

Terimakasih

**Comment by khannedy** [comment]
- tidak berkembang lagi (kemampuan / skill) di tempat kerja yang sekarang
- tidak ada inovasi yang dilakukan di tempat kerja
- punya atasan yang tidak kompeten di bidang nya, dan tidak mau menerima masukan
- sudah diterima di tempat kerja selanjutnya

bagaimana cara resign yang baik?
- lakukan one on one dengan atasan atau tim hrd, jauh2 hari sebelum resign
- pastikan semua perkerjaan sudah di deliver dengan baik
- lakukan transfer knowledge ke rekan kerja yang lainnya
